### ISSUE TITLE
我也是在Linux使用wine钉钉

### ISSUE THREAD

**Issue by JianleiZhang** [huataihuang/cloud-atlas#1]
之前的Web版被停了。你是在福报厂吗？

**Comment by huataihuang** [comment]
> 之前的Web版被停了。

停web版本实在是太low了，强迫引导到客户端，对Linux用户非常不友好。鹅厂的WeChat简单实用，支持web可以跨平台，才是良心。

> 你是在福报厂吗？

没错 :)

**Comment by huataihuang** [comment]
> 之前的Web版被停了。你是在福报厂吗？

我使用wine方式运行钉钉，中文输入是个麻烦，一直没有很好解决。临时的方法是在文本编辑器中写好内容，然后复制粘贴到钉钉再发出去，效率极低。

这个wine中文输入我一直没有搞定 - 我用的是fcitx

**Comment by JianleiZhang** [comment]
> > 之前的Web版被停了。你是在福报厂吗？
> 
> 我使用wine方式运行钉钉，中文输入是个麻烦，一直没有很好解决。临时的方法是在文本编辑器中写好内容，然后复制粘贴到钉钉再发出去，效率极低。
> 
> 这个wine中文输入我一直没有搞定 - 我用的是fcitx

我是Arch Linux，用的也是fcitx，可以输入文字发送信息，但是输入的文字不显示。

我现在宿主机是Windows 10，Linux跑在虚拟机里，要用钉钉就切到Win下。好累，感觉撑不住了…

**Comment by JianleiZhang** [comment]
我工作后一直用的是Linux，平常一般只起三个应用：xterm、emacs、chromium。换到Windows是不可能的，换工作还比较方便。

**Comment by huataihuang** [comment]
我曾经用Linux作为桌面有7~8年，各种折腾。不过公司给配MacBook，所以现在主要用macOS。

去年心血来潮在MacBook上折腾Arch Linux作为工作环境，虽然有些技术上的收获，但工作中使用的应用要在Linux上跑的话，时间和精力的代价太大。还是专注Linux的服务器技术为好。

**Comment by JianleiZhang** [comment]
我用Linux十几年了，云原始相关的我也有关注。现在是3台闲置的物理主机组了个集群，安装了Ceph+K8S。CICD用gitea+drone，服务和pipeline都跑在K8S上。
