### ISSUE TITLE
use netplan.io please

### ISSUE THREAD

**Issue by impl1874** [huataihuang/cloud-atlas#10]
https://github.com/huataihuang/cloud-atlas/blob/master/source/linux/ubuntu_linux/network/netplan.rst

**Comment by huataihuang** [comment]
> https://github.com/huataihuang/cloud-atlas/blob/master/source/linux/ubuntu_linux/network/netplan.rst

请问一下，是需要我修订什么内容？

please tell me which I need fix...

**Comment by impl1874** [comment]
> 这个版本的netplan可能是早期版本，只能固定读取 /var/lib/plan/netplan.dir/ ，不使用 /etc/netplan 目录，导致我配置无效。

出现这个问题的原因是没有完整的安装netplan，我在使用ubuntu18 rootfs安装netplan遇到了相同的问题，重新安装netplan.io解决了这个问题。
另外，如果这个文档能更新问题的解决方法，可能会帮助到更多的人。
如果可以，我也提交PR。

**Comment by impl1874** [comment]
**netplan.io**

> ubuntu@VM-0-4-ubuntu:~$ apt show netplan.io
Package: netplan.io
Version: 0.99-0ubuntu3~18.04.5
Priority: important
Section: net
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian netplan Maintainers <team+netplan@tracker.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 295 kB
Provides: nplan
Depends: libc6 (>= 2.27), libglib2.0-0 (>= 2.33.14), libnetplan0 (>= 0.99-0ubuntu3~18.04.5), libsystemd0 (>= 221), libuuid1 (>= 2.16), iproute2, python3, python3-yaml, python3-netifaces, systemd (>= 235-3ubuntu3)
Suggests: network-manager | wpasupplicant
Conflicts: netplan
Breaks: network-manager (<< 1.2.2-0ubuntu4~), nplan (<< 0.34~)
Replaces: nplan (<< 0.34~)
Homepage: https://netplan.io/
Task: minimal, ubuntu-core
Supported: 5y
Download-Size: 71.1 kB
APT-Sources: http://mirrors.tencentyun.com/ubuntu bionic-updates/main amd64 Packages
Description: YAML network configuration abstraction for various backends
 netplan reads YAML network configuration files which are written
 by administrators, installers, cloud image instantiations, or other OS
 deployments. During early boot it then generates backend specific
 configuration files in /run to hand off control of devices to a particular
 networking daemon.
 .
 Currently supported backends are networkd and NetworkManager.

**netplan**

> ubuntu@VM-0-4-ubuntu:~$ apt show netplan
Package: netplan
Version: 1.10.1-5build1
Priority: optional
Section: universe/misc
Source: plan
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Petter Reinholdtsen <pere@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 110 kB
Depends: adduser (>= 3.21), libc6 (>= 2.15)
Suggests: plan
Conflicts: plan (<< 1.7.1-1)
Replaces: plan (<< 1.7.1-1)
Homepage: http://www.bitrot.de/plan.html
Download-Size: 29.4 kB
APT-Sources: http://mirrors.tencentyun.com/ubuntu bionic/universe amd64 Packages
Description: network server for `plan'
 Plan is a schedule planner based on X/Motif.
 .
 Netplan adds to plan multiuser capability using an IP server.
 .
 WARNING: the best level of authentication offered by netplan in
 this version is identd.  That's quite weak, so watch the manpage and
 tune the config carefully.

**Comment by huataihuang** [comment]
感谢指正，也欢迎提交PR

希望能够提供比较详细的实践记录，解决问题的思路和成功/失败的经验

**Comment by huataihuang** [comment]
> > 这个版本的netplan可能是早期版本，只能固定读取 /var/lib/plan/netplan.dir/ ，不使用 /etc/netplan 目录，导致我配置无效。
> 
> 出现这个问题的原因是没有完整的安装netplan，我在使用ubuntu18 rootfs安装netplan遇到了相同的问题，重新安装netplan.io解决了这个问题。 另外，如果这个文档能更新问题的解决方法，可能会帮助到更多的人。 如果可以，我也提交PR。

我现在使用的Ubuntu 20.04.3 LTS ，刚才检查了一下，确实当前发行版已经使用了 netplan.io 替代了 netplan

```bash
$ apt list --installed | grep netplan

libnetplan0/focal-updates,now 0.103-0ubuntu5~20.04.5 amd64 [installed,automatic]
netplan.io/focal-updates,now 0.103-0ubuntu5~20.04.5 amd64 [installed,automatic]
```

**Comment by impl1874** [comment]
> > > 这个版本的netplan可能是早期版本，只能固定读取 /var/lib/plan/netplan.dir/ ，不使用 /etc/netplan 目录，导致我配置无效。
> > 
> > 
> > 出现这个问题的原因是没有完整的安装netplan，我在使用ubuntu18 rootfs安装netplan遇到了相同的问题，重新安装netplan.io解决了这个问题。 另外，如果这个文档能更新问题的解决方法，可能会帮助到更多的人。 如果可以，我也提交PR。
> 
> 我现在使用的Ubuntu 20.04.3 LTS ，刚才检查了一下，确实当前发行版已经使用了 netplan.io 替代了 netplan
> 
> ```shell
> $ apt list --installed | grep netplan
> 
> libnetplan0/focal-updates,now 0.103-0ubuntu5~20.04.5 amd64 [installed,automatic]
> netplan.io/focal-updates,now 0.103-0ubuntu5~20.04.5 amd64 [installed,automatic]
> ```

**Comment by impl1874** [comment]
> **netplan.io**
> 
> > ubuntu@VM-0-4-ubuntu:\~$ apt show netplan.io
> > Package: netplan.io
> > Version: 0.99-0ubuntu3\~18.04.5
> > Priority: important
> > Section: net
> > Origin: Ubuntu
> > Maintainer: Ubuntu Developers [ubuntu-devel-discuss@lists.ubuntu.com](mailto:ubuntu-devel-discuss@lists.ubuntu.com)
> > Original-Maintainer: Debian netplan Maintainers [team+netplan@tracker.debian.org](mailto:team+netplan@tracker.debian.org)
> > Bugs: https://bugs.launchpad.net/ubuntu/+filebug
> > Installed-Size: 295 kB
> > Provides: nplan
> > Depends: libc6 (>= 2.27), libglib2.0-0 (>= 2.33.14), libnetplan0 (>= 0.99-0ubuntu3\~18.04.5), libsystemd0 (>= 221), libuuid1 (>= 2.16), iproute2, python3, python3-yaml, python3-netifaces, systemd (>= 235-3ubuntu3)
> > Suggests: network-manager | wpasupplicant
> > Conflicts: netplan
> > Breaks: network-manager (<< 1.2.2-0ubuntu4~), nplan (<< 0.34~)
> > Replaces: nplan (<< 0.34~)
> > Homepage: https://netplan.io/
> > Task: minimal, ubuntu-core
> > Supported: 5y
> > Download-Size: 71.1 kB
> > APT-Sources: http://mirrors.tencentyun.com/ubuntu bionic-updates/main amd64 Packages
> > Description: YAML network configuration abstraction for various backends
> > netplan reads YAML network configuration files which are written
> > by administrators, installers, cloud image instantiations, or other OS
> > deployments. During early boot it then generates backend specific
> > configuration files in /run to hand off control of devices to a particular
> > networking daemon.
> > .
> > Currently supported backends are networkd and NetworkManager.
> 
> **netplan**
> 
> > ubuntu@VM-0-4-ubuntu:/~$ apt show netplan
> > Package: netplan
> > Version: 1.10.1-5build1
> > Priority: optional
> > Section: universe/misc
> > Source: plan
> > Origin: Ubuntu
> > Maintainer: Ubuntu Developers [ubuntu-devel-discuss@lists.ubuntu.com](mailto:ubuntu-devel-discuss@lists.ubuntu.com)
> > Original-Maintainer: Petter Reinholdtsen [pere@debian.org](mailto:pere@debian.org)
> > Bugs: https://bugs.launchpad.net/ubuntu/+filebug
> > Installed-Size: 110 kB
> > Depends: adduser (>= 3.21), libc6 (>= 2.15)
> > Suggests: plan
> > Conflicts: plan (<< 1.7.1-1)
> > Replaces: plan (<< 1.7.1-1)
> > Homepage: http://www.bitrot.de/plan.html
> > Download-Size: 29.4 kB
> > APT-Sources: http://mirrors.tencentyun.com/ubuntu bionic/universe amd64 Packages
> > Description: network server for `plan'
> > Plan is a schedule planner based on X/Motif.
> > .
> > Netplan adds to plan multiuser capability using an IP server.
> > .
> > WARNING: the best level of authentication offered by netplan in
> > this version is identd.  That's quite weak, so watch the manpage and
> > tune the config carefully.

**这个输出来自Ubuntu 18.04.4 LTS **
> ubuntu@VM-0-4-ubuntu:\~$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Comment by huataihuang** [comment]
@impl1874 感谢提供修正建议，已经将你提供的方法补充到文档中，非常感谢！
