### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by BM-laoli** [huataihuang/cloud-atlas#11]
非常感谢 作者的文章，这是一个从 “零开始的个人云☁️ ”，实操指南🧭 ，它给我带来了很多帮助。
本人从业web 开发，看了您的博文发现在JS领域您没有足够的精力去维护，申请成为这个领域的维护者

**Comment by huataihuang** [comment]
谢谢你提出这个请求

我撰写这个个人项目的目标是磨练技术，期望向全栈工程师发展(也许以后目标会不同)，所以我将我感兴趣的技术内容(和云计算相关)都逐步创建了分支。这种方式迫使我不断发现自己的不足以及不断的学习实践。

实际上这个项目接近于个人博客，只不过我选择了sphinx来完成，形成指南。

对于JS，目前我还没有入门，但是我有目标成为涉猎这方面的开发者，所以我近期在项目中学习这方面技术，把自己的想法变成现实。

我目前没有计划把这个项目变成一个协作完成的项目，主要是因为我目前还只是聚焦于个人实践，每一个分支都是我定下目标需要完成的实践目标，并不是追求成书的完整性和全面性。可能会比较慢，也可能始终无法完成某个分支的系统化手册，不过，目前我还没有放弃这个终极目标。

如果你也希望撰写JS相关书籍，你可以参考我的书籍架构创建一个新项目，或者在我的项目上fork出一个专注于JS手册项目。目前，这个项目我还是保持原先个人项目。

我所撰写的手册，欢迎你提供指正和建议，以及提出讨论技术相关的问题，我会尽我所能参与讨论。

再次感谢！

**Comment by huataihuang** [comment]
我今天在上班路上思考了一下这个项目:

* 这个项目的定位是 `一个人的云计算` ，目标是综合开源技术能够一个人构建起整个云计算基础架构
* 所有的文档都是经过 `实践` 并且不断打磨改进，而不是简单的汇总(毕竟网上学习资料汗牛充栋，不经过实践的知识不是真正掌握的知识)
* 给出详细的、可实践的、每一步都完备的技术文档，而不是仅仅是技术秀

由于我不断的在学习实践，整个 `Cloud Atlas` 的文档结构会不断调整变化，每一个分支都会随着我的知识技能增长而变化 - `就像一个圆，半径越大，周长 (知道自己不知道) 就越长` ，所以每个分支都是定下的挑战目标，每一步都要去独立完成。

就像个人博客，依然希望读者能够反馈 ( 提交 `issue` 讨论，提出修正 `pr` )，只不过由于文档结构和实践目标限制，每个分册我依然会独立完成。

`和时间赛跑` ，永不停步!
