### ISSUE TITLE
sphinxnotes-strike: Sphinx extension for HTML strikethrough text support - 这个方法我没有验证成功

### ISSUE THREAD

**Issue by SilverRainZ** [huataihuang/cloud-atlas#4]
Hello, 我是 sphinxnotes-strike 的作者，想了解下具体遇到什么问题了，方便提供一些信息么？

**Comment by huataihuang** [comment]
感谢你开源了 sphinxnotes-strike ，并且能够关注用户的问题

我参考 https://sphinx-notes.github.io/strike/ 试用了一下方法，也可能我没有理解正确的使用方法，导致最后没有实现 strike 效果

我执行的方法见 https://github.com/huataihuang/cloud-atlas/commit/d95715cecf390bd9fd715fae769974fefe35e0f7

- 安装

```bash
pip install sphinxnotes-strike
```
- 配置项目的 `conf.py` 添加:

```python
   extensions = [
             # …
             'sphinxnotes.strike',
             # …
             ]
```

- 然后撰写文档中加入

```
:strike:`Sphinx`
```

我本来以为能够直接看到 `Sphix` 上有划线，但是没有看到效果。

请指正一下方法，我对sphinx-doc只是简单使用，还有很多原理和方法不太了解。

多谢

**Comment by SilverRainZ** [comment]
我不确定你是在 `conf.py` 的何处添加的 `extension = { ...} `，对于你的文档来说，应该在 [42 行](https://github.com/huataihuang/cloud-atlas/blob/master/source/conf.py#L42) 进行修改：

```python
extensions = [
        'sphinx.ext.graphviz',
        'sphinxnotes.strike',
]
```

其他的步骤看起来没有任何问题，编译时有相关报错么？

**Comment by huataihuang** [comment]
编译时没有报错，我再试试，稍后答复你

**Comment by huataihuang** [comment]
我重新验证了一遍，这次是成功的。不过，我验证是在家里的电脑上搞的，新安装的sphinx环境，软件包版本都是最新的，测试成功。

* 文档我记录在 https://github.com/huataihuang/cloud-atlas/blob/master/source/devops/docs/sphinx_doc/sphinx_strike.rst
* 显示效果见 https://cloud-atlas.readthedocs.io/zh_CN/latest/devops/docs/sphinx_doc/sphinx_strike.html

 不过，我怀疑可能是我之前验证的环境有问题(sphinx版本比较陈旧)，因为这个环境在公司，我下周验证以后再更新这个issue。

**Comment by huataihuang** [comment]
> 我重新验证了一遍，这次是成功的。不过，我验证是在家里的电脑上搞的，新安装的sphinx环境，软件包版本都是最新的，测试成功。
> 
> * 文档我记录在 https://github.com/huataihuang/cloud-atlas/blob/master/source/devops/docs/sphinx_doc/sphinx_strike.rst
> * 显示效果见 https://cloud-atlas.readthedocs.io/zh_CN/latest/devops/docs/sphinx_doc/sphinx_strike.html
> 
> 不过，我怀疑可能是我之前验证的环境有问题(sphinx版本比较陈旧)，因为这个环境在公司，我下周验证以后再更新这个issue。

@SilverRainZ 我在之前验证失败的环境中， `git pull` 下来重新 `make html` 一次，发现现在生成的html中是正常显示strike效果的。

我回想了一下，我昨天 `make html` 之前，去掉了 `conf.py` 中的

```
 html_static_path = ['_static']

 #html_context = {
 #    'css_files': [
 #        '_static/theme_overrides.css',  # override wide tables in RTD theme
 #        ],
 #     }
```

这是因为我在使用新版本sphinx时候发现这个override不能正常工作(css)，所以我去掉以后做编译是正常显示 strike 效果的。我今天回到之前较低版本的sphinx环境中，保持上述去掉 `theme_overrides.css` ，则 `make html` 也能看到正确的 `strike` 效果。

我也验证了，确实是上述 `theme_overrides.css` 影响，如果恢复之前的配置

```
html_static_path = ['_static']

 html_context = {
     'css_files': [
         '_static/theme_overrides.css',  # override wide tables in RTD theme
         ],
      }
```

就会导致 `sphinxnotes-strike` 失效。

目前排查下来就是我的环境问题( `'_static/theme_overrides.css'` 影响)

**Comment by SilverRainZ** [comment]
对前端不太了解，但感觉 `_static/theme_overrides.css` 似乎不应该影响删除线的效果，我回头看看是什么原因。

**Comment by SilverRainZ** [comment]
推荐用 [html_css_files](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=project#confval-html_css_files) 来添加自定义的 CSS 文件，html_context 看起来会让插件自定义的 css 被覆盖，不止  sphinxnotes-strike，其他的插件在自定义了 html_context 之后都不可用了。
