### ISSUE TITLE
Docker目前不支持ext4的quota

### ISSUE THREAD

**Issue by michaelyu0906** [huataihuang/cloud-atlas#5]
文章里写到docker使用quota来限制overlay文件系统下容器的大小，
文章里写docker支持到ext4跟xfs的quota，
但经过文档查询以及实验验证发现目前docker仅支持xfs下的容器大小限制

**Comment by huataihuang** [comment]
> 文章里写到docker使用quota来限制overlay文件系统下容器的大小， 文章里写docker支持到ext4跟xfs的quota， 但经过文档查询以及实验验证发现目前docker仅支持xfs下的容器大小限制

感谢指正

根据Docker官方文档 [Set storage driver options per container](https://docs.docker.com/engine/reference/commandline/run/#set-storage-driver-options-per-container) :

```bash
 docker run -it --storage-opt size=120G fedora /bin/bash
```

> This (size) will allow to set the container rootfs size to 120G at creation time. This option is only available for the devicemapper, btrfs, overlay2, windowsfilter and zfs graph drivers. For the devicemapper, btrfs, windowsfilter and zfs graph drivers, user cannot pass a size less than the Default BaseFS Size. For the overlay2 storage driver, the size option is only available if the backing fs is xfs and mounted with the pquota mount option. Under these conditions, user can pass any size less than the backing fs size.

Docker官方文档指出只有底层文件系统是 ``xfs`` 情况(使用了 ``pquota`` 选项挂载)，才能在上层 ``overlay2`` 存储驱动中使用 ``--storage-opt size=XXX`` 来限制容器rootfs大小。

我已经修订了 [Docker容器规格Quota](https://github.com/huataihuang/cloud-atlas/blob/master/source/docker/storage/docker_size_quota.rst) 补充了一些资料：

目前国内互联网大厂通过修订Docker来实现基于EXT4文件系统作为后端FS，可以支持OverlayFS实现Quota，不过这个官方Docker有所不同。

我在撰写[Docker容器规格Quota](https://github.com/huataihuang/cloud-atlas/blob/master/source/docker/storage/docker_size_quota.rst)尚未做实践，这部分我后续再补充。最近几天正在搭建环境，会尽快完成。

谢谢

**Comment by michaelyu0906** [comment]
我查看了docker-ce最新的源码里quota部分的代码，里面提到了计划接下来将提供ext4的quota支持
![image](https://user-images.githubusercontent.com/12873232/141428221-ee226969-fcdb-4a41-b09c-57dded270850.png)

**Comment by huataihuang** [comment]
好的，我也关注一下，具体实践还是需要结合docker官方源代码来完成，文档更新可能还是落后于代码的。

多谢提示
